/**
 * Tools Command: GPT / AI Chat
 * Chat with AI (persistent conversation history via database)
 */
import fetch from 'node-fetch'
import { createProgressBar } from '../../lib/progress.js'

const MAX_HISTORY = 5

// Helper to get conversation history from database
function getConversationHistory(userId) {
  if (!global.db.data.aiConversations) {
    global.db.data.aiConversations = {}
  }
  if (!global.db.data.aiConversations[userId]) {
    global.db.data.aiConversations[userId] = []
  }
  return global.db.data.aiConversations[userId]
}

let handler = async (m, { conn, text, usedPrefix, command }) => {
  const userId = m.sender
  
  // Reset command
  if (command === 'resetai') {
    if (global.db.data.aiConversations) {
      delete global.db.data.aiConversations[userId]
    }
    return m.reply('✅ *Conversation history cleared!* Starting fresh.')
  }
  
  if (!text) {
    throw `*Please provide a message!*\n\nExample: *${usedPrefix}${command} Hello, how are you?*\n\n*Commands:*\n- *${usedPrefix}gpt* <message> - Chat with AI\n- *${usedPrefix}resetai* - Clear chat history`
  }
  
  const pb = createProgressBar(conn, m, { title: 'AI Chat', successMsg: 'Response generated!' })

  try {
    await pb.update(10, 'Thinking...')
    await m.react('🧠')
    await conn.sendPresenceUpdate('composing', m.chat)
    
    // Get history from database
    const conversationHistory = getConversationHistory(userId)
    await pb.update(30, 'Retrieving conversation history...')
    
    // Build Gemini content
    const contents = [
      {
        role: 'user',
        parts: [{ text: `You are ${global.botname || 'NEXUS-AI'}, a friendly and helpful WhatsApp assistant. You provide concise, accurate answers while being conversational. Keep responses relatively brief but complete.` }]
      },
      {
        role: 'model',
        parts: [{ text: 'Understood. I will provide helpful and concise responses as ' + (global.botname || 'NEXUS-AI') + '.' }]
      },
      ...conversationHistory.flatMap(h => [
        { role: 'user', parts: [{ text: h.user }] },
        { role: 'model', parts: [{ text: h.assistant }] }
      ]),
      { role: 'user', parts: [{ text: text }] }
    ]

    const apiKey = process.env.GEMINI_API_KEY
    if (!apiKey) {
      throw `*GEMINI_API_KEY* is not configured in .env!\n\nGet one for free at: https://aistudio.google.com/`
    }

    await pb.update(60, 'Communicating with Gemini...')
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ contents })
    })

    if (!response.ok) {
      const errorJson = await response.json().catch(() => ({}))
      throw new Error(errorJson.error?.message || `Gemini API error: ${response.statusText}`)
    }

    const data = await response.json()
    const aiResponse = data.candidates?.[0]?.content?.parts?.[0]?.text
    if (!aiResponse) throw new Error('No response generated by Gemini.')
    
    await pb.update(90, 'Finalizing...')
    await m.reply(aiResponse)
    await m.react('✅')
    await pb.finish(true)
    
    // Store in history (in database)
    conversationHistory.push({
      user: text,
      assistant: aiResponse,
      timestamp: Date.now()
    })
    
    // Limit history
    while (conversationHistory.length > MAX_HISTORY) {
      conversationHistory.shift()
    }
    
  } catch (e) {
    await m.react('❌')
    console.error(e)
    await pb.finish(false, e.message)
  }
}

handler.help = ['gpt <message>', 'ai <message>', 'resetai']
handler.tags = ['tools']
handler.command = ['gpt', 'ai', 'chatgpt', 'chat', 'resetai']
handler.desc = 'Chat with AI assistant'

export default handler
